#include <iostream>
#include<stdio.h>
#include<exception>
#include<stdexcept>

using namespace std;


int main ()
{
int a=10,b=0;
int c;
try
{
    throw "unknown";
}
catch(int error)
{
    cout<<"integer error occurred";
}
catch (...)
{
    cout<<"unknown exception";
}
    return 0;
}
